### ISSUE TITLE
cpu-and-gpu-selection-in-reinforcement-learning

### ISSUE THREAD

**Issue by deeepwin** [deeepwin/experience#2]

**Comment by bumie-e** [comment]
Thank you for sharing your experience! I was in a conversation with a founder who wants to support my current RL project by providing compute. But the question is how much compute do I need? The first phase of the project ran mostly on my M1 Air. I had to cut down training time so as to avoid blackouts(because I maxed out the memory). Now with a provider willing to provide compute support, the exact specs (memory, cpu, gpu, and training days) are quite difficult for me to quantify. 

I think your advice on CPU first seems like a good direction, and I would build on that premise.
